name: Build and Release

on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:

  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            target: aarch64-apple-darwin
          - platform: macos-latest
            target: x86_64-apple-darwin

          - platform: windows-latest
            target: x86_64-pc-windows-msvc
          - platform: windows-latest
            target: i686-pc-windows-msvc
          - platform: windows-latest
            target: aarch64-pc-windows-msvc

          - platform: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
          - platform: ubuntu-22.04-arm
            target: aarch64-unknown-linux-gnu

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: ${{ format('target/{0}/release/tplg{1}', matrix.target, contains(matrix.platform, 'windows') && '.exe' || '') }}

  create-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: create dist
        run: rm -rf dist && mkdir dist
      # mac
      - name: mv aarch64-apple-darwin
        run: mv artifacts/aarch64-apple-darwin/tplg dist/tplg-aarch64-apple-darwin
      - name: mv x86_64-apple-darwin
        run: mv artifacts/x86_64-apple-darwin/tplg dist/tplg-x64-apple-darwin
      # windows
      - name: mv x86_64-pc-windows-msvc
        run: mv artifacts/x86_64-pc-windows-msvc/tplg.exe dist/tplg-x64-pc-windows-msvc.exe
      - name: mv i686-pc-windows-msvc
        run: mv artifacts/i686-pc-windows-msvc/tplg.exe dist/tplg-x86-pc-windows-msvc.exe
      - name: mv aarch64-pc-windows-msvc
        run: mv artifacts/aarch64-pc-windows-msvc/tplg.exe dist/tplg-aarch64-pc-windows-msvc.exe
      # linux
      - name: mv aarch64-unknown-linux-gnu
        run: mv artifacts/aarch64-unknown-linux-gnu/tplg dist/tplg-aarch64-linux
      - name: mv x86_64-unknown-linux-gnu
        run: mv artifacts/x86_64-unknown-linux-gnu/tplg dist/tplg-amd64-linux

      
      - name: Generate changelog
        id: create_release
        run: npx changelogithub --name ${{ steps.vars.outputs.tag }} --assets dist/tplg-aarch64-apple-darwin,dist/tplg-x64-apple-darwin,dist/tplg-x64-pc-windows-msvc.exe,dist/tplg-x86-pc-windows-msvc.exe,dist/tplg-aarch64-pc-windows-msvc.exe,dist/tplg-aarch64-linux,dist/tplg-amd64-linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create package.json
        run: |
          VERSION=$(echo "${{ steps.vars.outputs.tag }}" | sed 's/^v//')
          echo '{"name":"tplg-binary","version":"$VERSION''","description":"tplg-binary"}' > dist/package.json 
      
      - name: publish npm
        run: cd dist && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
